export const userLoginConstant = {
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_ERROR: "USER_LOGIN_ERROR",
  USER_LOGIN_POP_UP_CENECL: "USER_LOGIN_POP_UP_CENECL",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
};
