export const userConstants = {
  SIGN_UP_REQUEST: "LOGIN_REQUEST",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_ERROR: "SIGN_UP_ERROR",
  SIGN_UP_ERROR_CENCEL: "SIGN_UP_ERROR_CENCEL",
  SIGN_UP_RETURN: "SING_UP_RETURN",
  SIGN_UP_VALIDATE_EMAIL: "SIGN_UP_VALIDATE_EMAIL",
  SIGN_UP_VALIDATE_COMPANY: "SIGN_UP_VALIDATE_COMPANY",
  SIGN_UP_VALIDATE_COMPANY_FALSE: "SIGN_UP_VALIDATE_COMPANY_FALSE",
  COMPANY_ADD_REQUEST: "COMPANY_ADD_REQUEST",
  COMPANY_ADD_SUCCESS: "COMPANY_ADD_SUCCESS",
  COMPANY_ADD_ERROR: "COMPANY_ADD_ERROR",
  REMOVE_BACK_SUCCESS: "REMOVE_BACK_SUCCESS",
};
