export const forgetConstants = {
  FORGET_PASSWORD_REQUEST: "FORGET_PASSWORD_REQUEST",
  FORGET_PASSWORD_SUCCESS: "FORGET_PASSWORD_SUCCESS",
  FORGET_PASSWORD_ERROR: "FORGET_PASSWORD_ERROR",
  FORGET_PASSWORD_ERROR_CENCEL: "FORGET_PASSWORD_ERROR_CENCEL",
  PASSWORD_UPDATE_SUCCESSFUL: "PASSWORD_UPDATE_SUCCESSFUL",
  PASSWORD_UPDATE_UNSUCCESSFUL: "PASSWORD_UPDATE_UNSUCCESSFUL",
};
