export const MagnifyConst = {
  CURRENT_USER_GET_DATA_SUCCESS: "CURRENT_USER_GET_DATA_SUCCESS",
  USER_POSTS_REQUEST: "USER_POST_REQUEST",
  USER_POSTS_SUCCESS: "USER_POST_SUCCESS",
  USER_POSTS_ERROR: "USER_POSTS_ERROR",
  VIDEO_REMOVE_SUCCESS: "VIDEO_REMOVE_SUCCESS",
  SHOW_DELETED_POST: "SHOW_DELETED_POST",
  GET_YOUTUBE_VIDEOS: "GET_YOUTUBE_VIDEOS",
  PAIDVIDEO_ANYLATICS: "PAIDVIDEO_ANYLATICS",
  GET_WALLETS_BALANCE: "GET_WALLETS_BALANCE",
  EMPTY_SATATE_USERPOSTS: "EMPTY_SATATE_USERPOSTS",
  FAVORITE_VIDEO_REQUEST: "FAVORITE_VIDEO_REQUEST",
  FAVORITE_VIDEO_SUCCESS: "FAVORITE_VIDEO_SUCCESS",
};
