export default [
  {
    _id: 1,
    title: "Clouds flowing over city time-lapse - 24 hours",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis, tortor vitae ullamcorper posuere, turpis risus sodales mauris, vitae posuere purus libero quis justo. Fusce dictum, sapien quis vulputate venenatis, lorem lectus vestibulum est.",
    platform: "YouTube",
    createdAt: new Date(2020, 4, 21),
    inContentStream: false,
    viewCount: 74823,
    watchTime: 60 * 60,
    originalAuthor: "SeanCullen",
    oipTransactionId: "Xjfgeibgrlshjbglauerbflbfglrubgf",
  },
  {
    _id: 2,
    title:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis, tortor vitae ullamcorper posuere, turpis risus sodales mauris, vitae posuere purus libero quis justo. #celebrate",
    platform: "Twitter",
    createdAt: new Date(2020, 6, 26),
    inContentStream: true,
    viewCount: 74823,
    watchTime: 60 * 60,
    originalAuthor: "SeanCullen",
    oipTransactionId: "Xjfgeibgrlshjbglauerbflbfglrubgf",
  },
  {
    _id: 3,
    title:
      "Covid-19 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis, tortor vitae ullamcorper posuere. #covid19",
    platform: "Instagram",
    createdAt: new Date(2020, 4, 21),
    inContentStream: true,
    viewCount: 74823,
    watchTime: 60 * 60,
    originalAuthor: "SeanCullen",
    oipTransactionId: "Xjfgeibgrlshjbglauerbflbfglrubgf",
  },
  {
    _id: 4,
    title: "Architecture. #design #architecture #sculpture",
    platform: "Instagram",
    createdAt: new Date(2020, 4, 21),
    inContentStream: true,
    viewCount: 74823,
    watchTime: 60 * 60,
    originalAuthor: "SeanCullen",
    oipTransactionId: "Xjfgeibgrlshjbglauerbflbfglrubgf",
  },
];
