export const AnylaticConstant = {
  FETCH_COMPANY_ANYLATICS_REQUEST: "FETCH_COMPANY_ANYLATICS_REQUEST",
  FETCH_COMPANY_ANYLATICS_SUCCESS: "FETCH_COMPANY_ANYLATICS_SUCCESS",
  FETCH_COMPANY_ANYLATICS_ERROR: "FETCH_COMPANY_ANYLATICS_ERROR",
};
