export const LOGIN = "LOGIN";

export const ADD_USER = "ADD_USER";

export const GET_YOUTUBE_VIDEO = "GET_YOUTUBE_VIDEO";

// video upload
export const SET_VIDEO_STEP = "SET_VIDEO_STEP";
export const ADD_VIDEO = "ADD_VIDEO";
export const SET_PLATEFORM = "SET_PLATEFORM";
export const SET_YOUTUBE_DATA = "SET_YOUTUBE_DATA";
export const SET_TWITTER_DATA = "SET_TWITTER_DATA";
export const SET_COLLABORATOR = "SET_COLLABORATOR";
export const RESET_VIDEO = "RESET_VIDEO";
export const SET_UPLOAD_PROGRESS = "SET_UPLOAD_PROGRESS";
export const SET_VIDEO_COLLABORATORS = "SET_VIDEO_COLLABORATORS";

// collaborator for dashboard (metrics)
export const SET_VIDEO_DATA_ANALYTICS = "SET_VIDEO_DATA_ANALYTICS";
export const SET_VIDEO_API_ANALYTICS = "SET_VIDEO_API_ANALYTICS";
export const SET_POST_COLLABORATORS = "SET_POST_COLLABORATORS";
export const SET_VIDEO_COLLABORATORS_STATISTICS =
  "SET_VIDEO_COLLABORATORS_STATISTICS";
export const RESET_DASHBOARD = "RESET_DASHBOARD";

export const UPDATE_VIDEO_COLLABORATORS_STATISTICS =
  "UPDATE_VIDEO_COLLABORATORS_STATISTICS";

export const SET_YOUTUBE_OWN_VIDEO = "SET_YOUTUBE_OWN_VIDEO";

export const UPDATE_YOUTUBE = "UPDATE_YOUTUBE";

export const TRANSACTION_ID = "TRANSACTION_ID";
export const SIA_URL_YT = "SIA_URL_YT";

export const REFRESH_DASHBOARD = "REFRESH_DASHBOARD";
export const ADD_OTHER_EMAILS_SUCCESS = "ADD_OTHER_EMAILS_SUCCESS";
export const GET_ADDTIONAL_EMAILS_SUCCESS = "GET_ADDTIONAL_EMAILS_SUCCESS";

//// add content stream videos ////
export const GET_VIDEO_CONTENT_STREAM_SUCCESS =
  "GET_VIDEO_CONTENT_STREAM_SUCCESS";
